In [123]:
### Author : Vasista
### Date   : 24/10/2018
### Topic  : KNN

In [124]:
# Problem Statement
# Whether to give Personal Loan or Not to the customer based on give Information.

In [125]:
# Import Required Packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [126]:
# Read Data
univbank = pd.read_csv('C:\\Piazza\\Activity Lab\\KNN_CollaborativeFiltering_Lab\\UnivBank.csv', na_values=['?', '#'])
# There are special charecters in place of Missing Values in data. replacing them with NAN
univbank.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1       0.0   
1   2   45          19      34     90089       3    1.5          1       0.0   
2   3   39          15      11     94720       1    1.0          1       0.0   
3   4   35           9     100     94112       1    2.7          2       0.0   
4   5   35           8      45     91330       4    1.0          2       0.0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                 1.0         0.0       0           0  
1              0                 1.0         0.0       0           0  
2              0                 0.0         0.0       0           0  
3              0                 0.0         NaN       0           0  
4              0                 0.0         0.0       0           1

In [127]:
#-------------- Descriptive Stats and Preprocessing ----------------#

In [128]:
# Removing unnecessary columns
univbank1= univbank.drop(['ID', 'ZIP Code'], axis=1)

In [129]:
# Descriptive stats and Preprocessing

univbank1.info()
univbank1.isnull().sum()   # there are few Missing Values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              4998 non-null float64
Personal Loan         5000 non-null int64
Securities Account    4998 non-null float64
CD Account            4999 non-null float64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(4), int64(8)
memory usage: 468.8 KB


Age                   0
Experience            0
Income                0
Family                0
CCAvg                 0
Education             0
Mortgage              2
Personal Loan         0
Securities Account    2
CD Account            1
Online                0
CreditCard            0
dtype: int64

In [ ]:
# As we can see there are few variables which are of integer_type but actually of Object_type.
# Typecast the data types for necessary variables. 

In [ ]:
# cat_var = univbank1[['Family', 'Education', 'Securities Account', 'CD Account', 'Online', 'CreditCard']]

In [130]:
# Fill Missing Values Using Central Tendencies
univbank1 = pd.DataFrame(univbank1.fillna(univbank1.mean()))  # Filling missin values with central Imputation
univbank1.isnull().sum()

Age                   0
Experience            0
Income                0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [101]:
 # Model Building Without changing the column types

In [131]:
univbank1.columns
univbank1.dtypes

Age                     int64
Experience              int64
Income                  int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage              float64
Personal Loan           int64
Securities Account    float64
CD Account            float64
Online                  int64
CreditCard              int64
dtype: object

In [135]:
# Changing only dtype of Y.
univbank1['Personal Loan'] = univbank1['Personal Loan'].astype('object')
univbank1.dtypes

Age                     int64
Experience              int64
Income                  int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage              float64
Personal Loan          object
Securities Account    float64
CD Account            float64
Online                  int64
CreditCard              int64
dtype: object

In [137]:
# Train Test Split
X = univbank1.loc[:, univbank1.columns != 'Personal Loan']
Y = univbank1[['Personal Loan']]
trainX, testX, trainY, testY = train_test_split(X, y, random_state = 10, test_size = 0.25)

In [155]:
# Model Fitting.
for i in range(1,6):
    knn = neighbors.KNeighborsClassifier(n_neighbors = i)
    knn.fit(trainX, trainY.values.ravel())        # Used values.ravel() to avoid warnings
    y_pred = knn.predict(testX)
    print(confusion_matrix(testY, y_pred))

[[657 239]
 [231 123]]
[[837  59]
 [322  32]]
[[747 149]
 [270  84]]
[[832  64]
 [324  30]]
[[769 127]
 [290  64]]


In [144]:
y_pred == 1

array([False, False, False, ..., False, False, False], dtype=bool)